name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: almalinux-9-s390x

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
